### ISSUE TITLE
觀影心得回饋

### ISSUE THREAD

**Issue by azole** [tuna0014hua/hello-git#1]
謝謝你的筆記，我們在 slack 已經討論過了，但想再跟你補充，你有這樣的朋友很棒耶，好好利用 XD 你朋友的觀念非常地好，我完全認同喔，我特別贊同「要可以教人到連對方都聽得懂為止」，這真的是考驗自己是不是真的懂了的一種很好的方式！

**Comment by tuna0014hua** [comment]
我會好好利用的 XDD
也謝謝老師 假日還與我一起討論~~
:smiley: :smiley: :smiley:

**Comment by tuna0014hua** [comment]
> 謝謝你的筆記，我們在 slack 已經討論過了，但想再跟你補充，你有這樣的朋友很棒耶，好好利用 XD 你朋友的觀念非常地好，我完全認同喔，我特別贊同「要可以教人到連對方都聽得懂為止」，這真的是考驗自己是不是真的懂了的一種很好的方式！


我會好好利用的 XDD
也謝謝老師 假日還與我一起討論~~
:smiley: :smiley: :smiley:
